// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkMHGcVpktWHf5wOwhBN4SzIBp5vGDw8o',
    appId: '1:1005119992926:web:26130893306dbad17970cf',
    messagingSenderId: '1005119992926',
    projectId: 'sevy3dprintercontroller',
    authDomain: 'sevy3dprintercontroller.firebaseapp.com',
    storageBucket: 'sevy3dprintercontroller.appspot.com',
    measurementId: 'G-L1GM8ZM475',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJxYwJvL-HHoyh_sZSBqEZ0of9pnrEg-Q',
    appId: '1:1005119992926:android:526abd09bd899c357970cf',
    messagingSenderId: '1005119992926',
    projectId: 'sevy3dprintercontroller',
    storageBucket: 'sevy3dprintercontroller.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyXSDueeG3WYoC5nhRmjOBbSnunwrK8MM',
    appId: '1:1005119992926:ios:018ac7122463ee507970cf',
    messagingSenderId: '1005119992926',
    projectId: 'sevy3dprintercontroller',
    storageBucket: 'sevy3dprintercontroller.appspot.com',
    iosBundleId: 'com.sevy.sevy3dPrinterController',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyXSDueeG3WYoC5nhRmjOBbSnunwrK8MM',
    appId: '1:1005119992926:ios:d315fcb5a752570b7970cf',
    messagingSenderId: '1005119992926',
    projectId: 'sevy3dprintercontroller',
    storageBucket: 'sevy3dprintercontroller.appspot.com',
    iosBundleId: 'com.sevy.sevy3dPrinterController.RunnerTests',
  );
}
